# Generated by Django 2.2.16 on 2020-11-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='tag',
        ),
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='全国知名', max_length=10, verbose_name='机构标签'),
        ),
    ]
